/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BenefitCard from "./BenefitCard";

const benefits = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d7cf4e510c98cd76a8b3d8e7b48d2c158911febdb635c105c012e6c1cbe52686?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4",
    title: "Transparent Process for Reliable and Fair Elections",
    description:
      "Our online blockchain voting system ensures the highest level of security and integrity, making it impossible to tamper with the results.",
    action: "Learn More",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d4522a024b18d51cb9c49d5ccb0524564849a3c0927f6493d19abae7206830bc?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4",
    title: "Effortless and User-Friendly Voting Experience",
    description:
      "Our platform is designed to be intuitive and easy to navigate, ensuring a smooth voting process for all users.",
    action: "Sign Up",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f54723db6b010c266b0184deecd31dc4e96d716802024d2c793358af83d6eafa?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4",
    title: "Secure and Reliable Voting System for Any Election",
    description:
      "Whether it's a small-scale local election or a large-scale national election, our system guarantees the security and accuracy of the voting process.",
    action: "Get Started",
  },
];

function Benefits() {
  return (
    <section className="flex overflow-hidden flex-col px-16 py-28 w-full bg-white max-md:px-5 max-md:py-24 max-md:max-w-full">
      <h2 className="self-center text-4xl font-bold leading-10 text-center text-black w-[768px] max-md:max-w-full">
        Experience Secure and Trustworthy Voting with Our Blockchain System
      </h2>
      <div className="flex flex-wrap gap-10 justify-center items-start mt-20 w-full max-md:mt-10 max-md:max-w-full">
        {benefits.map((benefit, index) => (
          <BenefitCard key={index} {...benefit} />
        ))}
      </div>
    </section>
  );
}

export default Benefits;
