/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

function Features() {
  return (
    <section className="flex overflow-hidden flex-col justify-center px-16 py-28 w-full bg-white max-md:px-5 max-md:py-24 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-center w-full max-md:max-w-full">
        <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full">
          <div className="flex flex-col w-full text-black max-md:max-w-full">
            <div className="flex flex-col w-full max-md:max-w-full">
              <p className="self-start text-base font-semibold text-center">
                Secure
              </p>
              <div className="flex flex-col mt-4 w-full max-md:max-w-full">
                <h2 className="text-5xl font-bold leading-[58px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
                  Ensuring Security and Transparency in Voting
                </h2>
                <p className="mt-6 text-lg leading-7 max-md:max-w-full">
                  Our blockchain voting system provides a secure and transparent
                  platform for elections. With the power of blockchain
                  technology, we ensure the integrity of the voting process,
                  giving voters peace of mind.
                </p>
              </div>
            </div>
            <div className="flex flex-wrap gap-6 items-start py-2 mt-8 w-full max-md:max-w-full">
              <div className="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
                <p className="text-5xl font-bold leading-tight max-md:text-4xl">
                  50%
                </p>
                <p className="mt-2 text-base">
                  Secure and tamper-proof voting records
                </p>
              </div>
              <div className="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
                <p className="text-5xl font-bold leading-tight max-md:text-4xl">
                  50%
                </p>
                <p className="mt-2 text-base leading-6">
                  Transparent and verifiable election results
                </p>
              </div>
            </div>
          </div>
          <div className="flex gap-6 items-center self-start pt-4 mt-6 text-base text-black">
            <Button variant="outline">Learn More</Button>
            <a
              href="#"
              className="flex gap-2 justify-center items-center self-stretch my-auto"
            >
              <span className="self-stretch my-auto">Sign Up</span>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9cc59fc65142f42773e3131d8a5a5a8d452f8191d61b72aca044880ddbb310ec?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </a>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/7264cd4b8f88470d079feb3a7d1afa2c513f096f5ccfab0746ae21c3ead3c3c1?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4"
          alt="Blockchain voting system illustration"
          className="object-contain flex-1 shrink self-stretch my-auto w-full aspect-[0.96] basis-0 min-w-[240px] max-md:max-w-full"
        />
      </div>
    </section>
  );
}

export default Features;
