/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

function Hero() {
  return (
    <section className="flex overflow-hidden flex-wrap gap-10 items-center px-16 py-28 w-full bg-white max-md:px-5 max-md:py-24 max-md:max-w-full">
      <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full">
        <div className="flex flex-col w-full text-black max-md:max-w-full">
          <h1 className="text-6xl font-bold leading-[67px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
            Welcome to our Secure Online Voting System
          </h1>
          <p className="mt-6 text-lg leading-7 max-md:max-w-full">
            Experience the power of blockchain technology in ensuring
            transparent and tamper-proof elections.
          </p>
        </div>
        <div className="flex gap-4 items-start self-start pt-4 mt-6 text-base">
          <Button variant="primary">Start</Button>
          <Button variant="secondary">Learn More</Button>
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1b01412aadab88bc12f885732910b024141ed2de9e92df62d53791f134779745?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4"
        alt="Secure Online Voting System illustration"
        className="object-contain flex-1 shrink self-stretch my-auto w-full aspect-[0.96] basis-0 min-w-[240px] max-md:max-w-full"
      />
    </section>
  );
}

export default Hero;
