/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PageGroup from "./PageGroup";
import Button from "./Button";

const pageGroups = [
  {
    title: "Group One Pages",
    pages: [
      { title: "Page One", description: "Learn More" },
      { title: "Page Two", description: "Learn More" },
      { title: "Page Three", description: "Learn More" },
      { title: "Page Four", description: "Learn More" },
    ],
  },
  {
    title: "Group Two Pages",
    pages: [
      { title: "Page Five", description: "Learn More" },
      { title: "Page Six", description: "Learn More" },
      { title: "Page Seven", description: "Learn More" },
      { title: "Page Eight", description: "Learn More" },
    ],
  },
  {
    title: "Group Three Pages",
    pages: [
      { title: "Page Nine", description: "Learn More" },
      { title: "Page Ten", description: "Learn More" },
      { title: "Page Eleven", description: "Learn More" },
      { title: "Page Twelve", description: "Learn More" },
    ],
  },
];

function MainContent() {
  return (
    <main className="flex overflow-hidden flex-wrap self-center w-full max-md:max-w-full">
      <div className="flex flex-wrap flex-1 shrink gap-8 items-start self-start py-8 pr-8 pl-16 basis-0 min-w-[240px] max-md:px-5 max-md:max-w-full">
        {pageGroups.map((group, index) => (
          <PageGroup key={index} {...group} />
        ))}
      </div>
      <aside className="flex flex-col justify-center py-8 pr-16 pl-8 w-80 text-sm text-black bg-zinc-100 min-w-[240px] max-md:px-5">
        <div className="flex flex-col w-full">
          <h2 className="font-semibold text-black">Group Four Pages</h2>
          <nav>
            <ul>
              {[
                "Link One",
                "Link Two",
                "Link Three",
                "Link Four",
                "Link Five",
              ].map((link, index) => (
                <li key={index} className="mt-4">
                  <a href="#">{link}</a>
                </li>
              ))}
            </ul>
          </nav>
        </div>
      </aside>
    </main>
  );
}

export default MainContent;
