/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PageLink from "./PageLink";

function PageGroup({ title, pages }) {
  return (
    <div className="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
      <h2 className="text-sm font-semibold text-black">{title}</h2>
      {pages.map((page, index) => (
        <PageLink key={index} {...page} />
      ))}
    </div>
  );
}

export default PageGroup;
