/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PageLink({ title, description }) {
  return (
    <div className="flex gap-3 items-start py-2 mt-4 w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8e7f596d92c33ccbdfab1ef15c3c20fe447a7fc056c87e930302841e63faea14?placeholderIfAbsent=true&apiKey=549c322b647e496e99a9065b5f46d9e4"
        alt=""
        className="object-contain shrink-0 w-6 aspect-square"
      />
      <div className="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
        <h3 className="text-base font-semibold text-black">{title}</h3>
        <p className="text-sm text-black">{description}</p>
      </div>
    </div>
  );
}

export default PageLink;
